### PR TITLE
Allow default value for missing XML elements

### PR DESCRIPTION
**Pull request by redmcg**
I'm not sure if you're still accepting PRs - but I added a simple feature that allows the provision of a default value if an XML element is missing.

### CODE REVIEW

**Comment by toyokazu** [comment]
I understand your requirements and merge your PR. Thank you for your contribution!

**Comment by redmcg** [comment]
Thanks for that. Are you interested in upgrading the plugin to support Fluentd v0.14 and above? I've done some work to upgrade it (it's not finished yet) - but if you're interested - I'll send another PR once done.

**Comment by toyokazu** [comment]
Thank you for your proposal! As I already wrote in the different thread, currently I don’t need this plugin and difficult to have time to maintain. But if you can contribute it, I’m willing to marge your contribution and it will help guys struggling with XML logs. In this case, I’m sorry that I may have to rely on you for every update and test of this project. If you are interested in, I can add you as a contributor of this project. Please also consider it. In that case, it may still be an issue to pass rubygems repository...
Anyway, thank you for your good suggestion! It is a desirable aspect of open source :)

**Comment by redmcg** [comment]
I would be happy to be a co-contributor. I've never contributed to the rubygems repository before, but I'm also happy to research that process.

**Comment by toyokazu** [comment]
Thank you for your acceptance! I just added you as a contributor. I'm not sure the detail of what a contributor can do. Please try it and if you cannot make what you want to do there, please let me know. Unfortunately, I don't know how to share rubygems repository with the other guys. If you find a way, please let me know. I'll try it.

**Comment by redmcg** [comment]
No problem - and thank-you.

**Comment by toyokazu** [comment]
Hmm, this may be an answer to the previous post.

https://help.rubygems.org/discussions/questions/151-adding-another-owner

If you are interested in, please let me know your e-mail for managing rubygems.

**Comment by redmcg** [comment]
You can use brendan@redmandi.com

**Comment by toyokazu** [comment]
Thanks! I just added your e-mail as an owner of the repository (https://rubygems.org/gems/fluent-plugin-xml-parser).

Best Regards

**Pull request merged**
